name: Android Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Generate Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: app/build/reports/jacoco/html/
    
    - name: Extract File-wise Coverage
      run: |
        echo "Extracting file-wise coverage percentages..."
        awk -v RS='<tr>' '
          match($0, /href="([^"]+)"/, file) && match($0, /<td class="ctr2" id="c8">([0-9]+%)/, cov) {
            gsub("/", ".", file[1]);  # Replace / with . in filenames
            print file[1] ": " cov[1];
          }
        ' app/build/reports/jacoco/html/index.html > coverage_results.txt

        if [ ! -s coverage_results.txt ]; then
          echo "Failed to extract file-wise coverage percentages"
          exit 1
        fi

        echo "Coverage Percentages Found:"
        cat coverage_results.txt
