name: Android Coverage Report

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate-coverage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Generate Coverage Report
      run: ./gradlew jacocoTestReport
    
    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: app/build/reports/jacoco/html/
    
    - name: Extract Coverage Percentage
      run: |
        # Extract coverage percentage for the specific href="be.scri/index.html"
        coverage=$(awk -v RS='<tr>' '/href="be.scri\/index.html"/ {match($0, /<td class="ctr2" id="c8">([0-9]+%)/, arr); print arr[1]}' app/build/reports/jacoco/html/index.html)

        if [ -z "$coverage" ]; then
          echo "Failed to extract coverage percentage"
          exit 1
        fi
        
        echo "Total Coverage for be.scri: $coverage"
